# server port config
server:
  port: 8001
  error:
    whitelabel:
      enabled: false
    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부
    

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: root
    hikari:
      auto-commit: false


    
  # jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true

  thymeleaf:
    cache: false # 기본 값 true / 개발 중 변경 사항 즉시 확인하기 위해 캐시 false
    
    

